services:
  ratings:
    build: ~/itkmitl-devops-assignments/ratings/.
    image: ghcr.io/konlawatit/itkmitl-bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    volumes:
      - ~/itkmitl-devops-assignments/ratings/databases:/docker-entrypoint-initdb.d
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings
  details:
    build:  ~/itkmitl-devops-assignments/details/.
    image: ghcr.io/konlawatit/itkmitl-bookinfo-details:dev
    ports:
      - "8081:8081"
  reviews:
    build: ~/itkmitl-devops-assignments/reviews/.
    image: ghcr.io/konlawatit/itkmitl-bookinfo-ratings:devi
    ports:
      - "8082:9080"
    environment:
      RATINGS_SERVICE: http://ratings:8080
      ENABLE_RATINGS: "true"
  productpage:
    build: ~/itkmitl-devops-assignments/productpage/.
    image: ghcr.io/konlawatit/itkmitl-bookinfo-productpage:dev
    ports:
      - "8083:9080"
    environment:
      DETAILS_HOSTNAME: http://details:8081
      RATINGS_HOSTNAME: http://ratings:8080
      REVIEWS_HOSTNAME: http://reviews:9080